version: "3.3"

services:

  gateway:
    image: ghcr.io/tomasz-galuszka/gateway:${SERVICE_VERSION}
    container_name: gateway-service
    networks:
      default:
        aliases:
          - tematzycie.pl
    ports:
      - "80:80"
      - "443:443"
    environment:
      SERVICE_TEMAT_ZYCIE_PL_HOST: tematzycie-service
      SERVICE_TEMAT_ZYCIE_PL_PORT: 80
    volumes:
      - ./certbot/certs:/etc/letsencrypt

  tematzycie-service:
    image: nginx:${NGINX_VERSION}
    volumes:
      - ./stubs/tematzycie-service.html:/usr/share/nginx/html/index.html