version: "3.3"

services:

  gateway-service:
    image: ghcr.io/tomasz-galuszka/gateway-service:latest-local
    ports:
      - "80:80"
    environment:
      SERVICE_BLOG_XMANAGER_OVH_HOST: blog-service
      SERVICE_BLOG_XMANAGER_OVH_PORT: 80
      SERVICE_TEMAT_ZYCIE_PL_HOST: tematzycie-service
      SERVICE_TEMAT_ZYCIE_PL_PORT: 80
      SERVICE_WEBSPIDER_XMANAGER_OVH_HOST: webspider-service
      SERVICE_WEBSPIDER_XMANAGER_OVH_PORT: 80
      SERVICE_XMANAGER_OVH_HOST: xmanager-service
      SERVICE_XMANAGER_OVH_PORT: 80

  blog-service:
    image: nginx:latest
    volumes:
      - ./stubs/blog-service.html:/usr/share/nginx/html/index.html

  tematzycie-service:
    image: nginx:latest
    volumes:
      - ./stubs/tematzycie-service.html:/usr/share/nginx/html/index.html

  webspider-service:
    image: nginx:latest
    volumes:
      - ./stubs/webspider-service.html:/usr/share/nginx/html/index.html

  xmanager-service:
    image: nginx:latest
    volumes:
      - ./stubs/xmanager-service.html:/usr/share/nginx/html/index.html