services:

  gateway-service:
    image: ghcr.io/tomasz-galuszka/gateway:${SERVICE_VERSION}
    container_name: gateway-service
    networks:
      default:
        aliases:
          - tematzycie.pl
          - tech.tematzycie.pl
    ports:
      - "80:80"
      - "443:443"
    environment:
      SERVICE_TEMAT_ZYCIE_PL_HOST: tematzycie-service
      SERVICE_TEMAT_ZYCIE_PL_PORT: 80
      SERVICE_TECH_TEMAT_ZYCIE_PL_HOST: tech-tematzycie-service
      SERVICE_TECH_TEMAT_ZYCIE_PL_PORT: 80
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt

  tematzycie-service:
    container_name: tematzycie-service
    image: nginx:${NGINX_VERSION}
    volumes:
      - ./stubs/tematzycie-service.html:/usr/share/nginx/html/index.html

  tech-tematzycie-service:
    container_name: tech-tematzycie-service
    image: nginx:${NGINX_VERSION}
    volumes:
      - ./stubs/tech-tematzycie-service.html:/usr/share/nginx/html/index.html

  expensemanager-site-service:
    container_name: expensemanager-site-service
    image: nginx:${NGINX_VERSION}
    volumes:
      - ./stubs/expensemanager.site-service.html:/usr/share/nginx/html/index.html