name: Build package

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Release new tag"]
    types:
      - completed

jobs:

  build-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: '0'
      - uses: rlespinasse/github-slug-action@v3.x
      - name: build
        run: |
          NEW_VERSION=$(git describe --tags --abbrev=0 | awk -F. '{OFS="."; $NF+=1; print $0})
          
          make VERSION="$NEW_VERSION" build-remote REPOSITORY_USER="tomasz-galuszka" REPOSITORY_PASSWORD="${{secrets.GITHUB_TOKEN}}"
          make VERSION="$NEW_VERSION" build-sidecar-remote REPOSITORY_USER="tomasz-galuszka" REPOSITORY_PASSWORD="${{secrets.GITHUB_TOKEN}}"
          
          
